import { useMemo, useState } from 'react'
import { ArrowRight, Check, GitCompare, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Category, Tool } from '../lib/types'

interface Props { tools: Tool[]; categories: Category[] }
export default function ComparePage({ tools, categories }: Props) {
  const [selected, setSelected] = useState<string[]>([])
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : current.length < 6 ? [...current, id] : current)
  const selectedTools = useMemo(() => tools.filter(tool => selected.includes(tool.id)), [tools, selected])
  const fields: { key: string; label: string; getValue: (tool: Tool) => string }[] = [
    { key: 'category', label: 'Category', getValue: tool => categories.find(category => category.id === tool.category)?.title || tool.category || 'Unknown' },
    { key: 'open_source', label: 'Open Source', getValue: tool => tool.open_source ? 'Yes' : tool.open_source === false ? 'No' : 'Unknown' },
    { key: 'byok', label: 'BYOK', getValue: tool => tool.byok ? 'Yes' : tool.byok === false ? 'No' : 'Unknown' },
    { key: 'local_models', label: 'Local Models', getValue: tool => tool.local_models ? 'Yes' : tool.local_models === false ? 'No' : 'Unknown' },
    { key: 'mcp', label: 'MCP', getValue: tool => tool.mcp ? 'Yes' : tool.mcp === false ? 'No' : 'Unknown' },
    { key: 'vscode', label: 'VS Code', getValue: tool => tool.vscode ? 'Yes' : tool.vscode === false ? 'No' : 'Unknown' },
    { key: 'cli', label: 'CLI', getValue: tool => tool.cli ? 'Yes' : tool.cli === false ? 'No' : 'Unknown' },
    { key: 'desktop', label: 'Desktop', getValue: tool => tool.desktop ? 'Yes' : tool.desktop === false ? 'No' : 'Unknown' },
    { key: 'free', label: 'Free', getValue: tool => tool.free ? 'Yes' : tool.free === false ? 'No' : 'Unknown' },
    { key: 'autonomy_level', label: 'Autonomy', getValue: tool => tool.autonomy_level !== undefined ? `${tool.autonomy_level}/5` : 'Unknown' },
    { key: 'license', label: 'License', getValue: tool => tool.license || 'Unknown' },
    { key: 'status', label: 'Status', getValue: tool => tool.status || 'Unknown' },
  ]
  return <div className="relative overflow-hidden"><div className="page-grid pointer-events-none absolute inset-x-0 top-0 h-80" /><div className="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="reveal mb-10 flex flex-col justify-between gap-5 border-b border-white/10 pb-8 sm:flex-row sm:items-end"><div><div className="eyebrow flex items-center gap-2"><GitCompare size={13} /> Make the call</div><h1 className="mt-4 font-display text-4xl font-semibold text-white sm:text-5xl">Compare with<br /><span className="text-[#8fe5e5]">clarity.</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-[#8da6b2]">Put up to six tools side by side and see what actually changes for your workflow.</p></div><div className="text-sm text-[#78929e]"><strong className="block text-2xl font-semibold text-white">{selected.length}<span className="text-[#607b87]">/6</span></strong> selected</div></div>
    <div className="glass-panel mb-8 rounded-2xl p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-semibold text-white">Choose your shortlist</p><p className="mt-1 text-xs text-[#718b96]">Select at least two tools to unlock the comparison.</p></div>{selected.length > 0 && <button onClick={() => setSelected([])} className="inline-flex items-center gap-1 text-xs font-semibold text-[#8fe5e5] hover:text-white">Clear <X size={13} /></button>}</div><div className="flex max-h-52 flex-wrap gap-2 overflow-y-auto pr-1">{tools.map(tool => <button key={tool.id} onClick={() => toggle(tool.id)} className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-semibold transition ${selected.includes(tool.id) ? 'border-[#7edce3]/40 bg-[#7edce3]/10 text-[#9becef]' : 'border-white/10 bg-white/[.025] text-[#829ba6] hover:border-white/20 hover:text-white'}`}>{selected.includes(tool.id) && <Check size={13} />}{tool.name}</button>)}</div></div>
    {selectedTools.length < 2 ? <div className="glass-panel rounded-2xl px-6 py-20 text-center"><GitCompare size={28} className="mx-auto text-[#5f818e]" /><p className="mt-4 text-lg font-semibold text-white">Your comparison is ready when you are</p><p className="mt-2 text-sm text-[#819aa5]">Choose two or more tools above to see their differences at a glance.</p></div> : <><div className="glass-panel hidden overflow-x-auto rounded-2xl md:block"><table className="w-full border-collapse"><thead><tr><th className="sticky left-0 border-b border-white/10 bg-[#0e1d27] p-4 text-left text-xs font-mono uppercase tracking-wider text-[#718b96]">Feature</th>{selectedTools.map(tool => <th key={tool.id} className="min-w-[140px] border-b border-white/10 p-4 text-left text-sm font-semibold text-white"><Link to={`/tools/${tool.id}`} className="hover:text-[#9becef]">{tool.name}</Link></th>)}</tr></thead><tbody>{fields.map(field => <tr key={field.key} className="transition hover:bg-white/[.025]"><td className="sticky left-0 border-b border-white/5 bg-[#0e1d27] p-4 text-sm font-medium text-[#8aa3ae]">{field.label}</td>{selectedTools.map(tool => <td key={tool.id} className="border-b border-white/5 p-4 text-sm text-[#c2d4da]">{field.getValue(tool)}</td>)}</tr>)}</tbody></table></div><div className="space-y-4 md:hidden">{selectedTools.map(tool => <div key={tool.id} className="surface-panel rounded-2xl p-5"><Link to={`/tools/${tool.id}`} className="flex items-center justify-between text-lg font-semibold text-white hover:text-[#9becef]">{tool.name}<ArrowRight size={16} className="text-[#6d8994]" /></Link><div className="mt-4 space-y-3">{fields.map(field => <div key={field.key} className="flex justify-between gap-4 text-sm"><span className="text-[#718b96]">{field.label}</span><span className="text-right text-[#c2d4da]">{field.getValue(tool)}</span></div>)}</div></div>)}</div></>}
  </div></div>
}