import { useMemo, useState } from 'react'
import { ArrowUpRight, Check, Filter, Search, SlidersHorizontal, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import type { Category, Tool } from '../lib/types'

interface Props { tools: Tool[]; categories: Category[] }

export default function ToolsPage({ tools, categories }: Props) {
  const [params, setParams] = useSearchParams()
  const [search, setSearch] = useState('')
  const [cat, setCat] = useState(params.get('category') || 'all')
  const [status, setStatus] = useState('all')
  const [filterOpen, setFilterOpen] = useState(false)
  const [filters, setFilters] = useState({ oss: false, byok: false, mcp: false, free: false, vscode: false, cli: false })
  const statuses = useMemo(() => Array.from(new Set(tools.map(tool => tool.status || 'unknown'))).sort(), [tools])
  const filtered = useMemo(() => {
    let result = tools
    if (search) { const query = search.toLowerCase(); result = result.filter(tool => tool.name.toLowerCase().includes(query) || tool.description?.toLowerCase().includes(query) || tool.best_for?.toLowerCase().includes(query) || tool.tags?.some(tag => tag.toLowerCase().includes(query)) || tool.capabilities?.some(capability => capability.toLowerCase().includes(query))) }
    if (cat !== 'all') result = result.filter(tool => tool.category === cat)
    if (status !== 'all') result = result.filter(tool => (tool.status || 'unknown') === status)
    if (filters.oss) result = result.filter(tool => tool.open_source)
    if (filters.byok) result = result.filter(tool => tool.byok)
    if (filters.mcp) result = result.filter(tool => tool.mcp)
    if (filters.free) result = result.filter(tool => tool.free || tool.free_tier)
    if (filters.vscode) result = result.filter(tool => tool.vscode)
    if (filters.cli) result = result.filter(tool => tool.cli)
    return result
  }, [tools, search, cat, status, filters])
  const activeFilterCount = Object.values(filters).filter(Boolean).length + (cat !== 'all' ? 1 : 0) + (status !== 'all' ? 1 : 0)
  const reset = () => { setSearch(''); setCat('all'); setStatus('all'); setFilters({ oss: false, byok: false, mcp: false, free: false, vscode: false, cli: false }); setParams({}) }
  const chooseCategory = (value: string) => { setCat(value); value === 'all' ? setParams({}) : setParams({ category: value }) }

  return <div className="relative min-h-full overflow-hidden"><div className="page-grid pointer-events-none absolute inset-x-0 top-0 h-96" /><div className="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
    <div className="reveal flex flex-col justify-between gap-6 border-b border-white/10 pb-8 lg:flex-row lg:items-end"><div><div className="eyebrow flex items-center gap-2"><SlidersHorizontal size={13} /> The tool index</div><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight text-white sm:text-5xl">Find your next<br /><span className="text-[#8fe5e5]">building block.</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-[#8da6b2]">Search {tools.length} developer tools by what they do, where they run, and how they fit your workflow.</p></div><div className="flex gap-5 text-sm text-[#78929e]"><span><strong className="block text-2xl font-semibold text-white">{tools.length}</strong> indexed</span><span><strong className="block text-2xl font-semibold text-white">{categories.length}</strong> categories</span></div></div>
    <div className="tools-controls mt-8 grid gap-3 lg:grid-cols-[1fr_auto]"><label className="glass-panel flex items-center gap-3 rounded-xl px-4 py-3.5"><Search size={18} className="text-[#f5c542]" /><input aria-label="Search tools" type="search" placeholder="Search by name, capability, or use case..." value={search} onChange={event => setSearch(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-[#607b87]" />{search && <button aria-label="Clear search" onClick={() => setSearch('')} className="text-[#718b96] hover:text-white"><X size={16} /></button>}<kbd className="hidden rounded border border-white/10 px-2 py-1 text-[10px] text-[#66808c] sm:block">⌘ K</kbd></label><button onClick={() => setFilterOpen(value => !value)} className="button-secondary inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold transition"><Filter size={16} /> Filters {activeFilterCount > 0 && <span className="grid h-5 min-w-5 place-items-center rounded-full bg-[#f5c542] px-1 text-[11px] font-bold text-[#111315]">{activeFilterCount}</span>}</button></div>
    <div className={`${filterOpen ? 'grid' : 'hidden'} mt-3 gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4 md:grid-cols-2 lg:grid-cols-4`}><Select label="Category" value={cat} onChange={chooseCategory} options={[{ value: 'all', label: 'All categories' }, ...categories.map(category => ({ value: category.id, label: category.title || category.name || category.id }))]} /><Select label="Status" value={status} onChange={setStatus} options={[{ value: 'all', label: 'All statuses' }, ...statuses.map(value => ({ value, label: value }))]} /><div className="md:col-span-2"><p className="mb-2 text-[11px] font-mono uppercase tracking-wider text-[#718b96]">Signals</p><div className="flex flex-wrap gap-2">{[['oss', 'Open source'], ['byok', 'BYOK'], ['mcp', 'MCP'], ['free', 'Free tier'], ['vscode', 'VS Code'], ['cli', 'CLI']].map(([key, label]) => <Toggle key={key} label={label} active={filters[key as keyof typeof filters]} onClick={() => setFilters(current => ({ ...current, [key]: !current[key as keyof typeof filters] }))} />)}</div></div></div>
    <div className="mt-8 flex items-center justify-between gap-4"><p className="text-sm text-[#819aa5]">Showing <strong className="text-white">{filtered.length}</strong> of {tools.length} tools</p>{activeFilterCount > 0 && <button onClick={reset} className="inline-flex items-center gap-1 text-xs font-semibold text-[#8fe5e5] hover:text-white">Clear filters <X size={13} /></button>}</div>
    {filtered.length === 0 ? <div className="glass-panel mt-5 rounded-2xl px-6 py-20 text-center"><Search size={25} className="mx-auto text-[#5f818e]" /><p className="mt-4 text-lg font-semibold text-white">No tools match that search</p><p className="mt-2 text-sm text-[#819aa5]">Try a broader term or clear one of your filters.</p><button onClick={reset} className="button-secondary mt-6 rounded-lg px-4 py-2 text-sm font-semibold">Reset explorer</button></div> : <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((tool, index) => <ToolCard key={tool.id} tool={tool} delay={index % 6} />)}</div>}
  </div></div>
}

function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label><span className="mb-2 block text-[11px] font-mono uppercase tracking-wider text-[#718b96]">{label}</span><select value={value} onChange={event => onChange(event.target.value)} className="w-full rounded-lg border border-white/10 bg-[#0d1d27] px-3 py-2.5 text-sm text-[#c2d4da] outline-none transition focus:border-[#7edce3]/50">{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label> }
function Toggle({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold transition ${active ? 'border-[#7edce3]/40 bg-[#7edce3]/10 text-[#9becef]' : 'border-white/10 bg-white/[.025] text-[#829ba6] hover:border-white/20 hover:text-white'}`}><span className={`grid h-3.5 w-3.5 place-items-center rounded border ${active ? 'border-[#7edce3] bg-[#7edce3] text-[#081018]' : 'border-[#5b7783]'}`}>{active && <Check size={10} strokeWidth={3} />}</span>{label}</button> }
function ToolCard({ tool, delay }: { tool: Tool; delay: number }) { const category = tool.category?.replace(/-/g, ' ').replace(/\b\w/g, value => value.toUpperCase()) || 'Unknown'; return <Link to={`/tools/${tool.id}`} className="resource-card interactive group reveal rounded-2xl p-5" style={{ animationDelay: `${delay * 45}ms` }}><div className="flex items-start justify-between gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#7edce3]/10 font-display text-lg font-semibold text-[#8fe5e5]">{tool.name.charAt(0)}</div><div className="flex items-center gap-2">{tool.open_source && <span className="rounded-full border border-[#72d5b3]/25 bg-[#72d5b3]/10 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-[#7de0bc]">OSS</span>}<ArrowUpRight size={16} className="text-[#607c87] transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[#8fe5e5]" /></div></div><p className="mt-5 text-[11px] font-mono uppercase tracking-wider text-[#6f8b96]">{category}</p><h2 className="mt-2 truncate text-lg font-semibold text-white group-hover:text-[#9becef]">{tool.name}</h2><p className="mt-2 line-clamp-2 min-h-12 text-sm leading-6 text-[#839ca7]">{tool.description}</p><div className="mt-5 flex flex-wrap gap-1.5 border-t border-white/8 pt-4">{tool.mcp && <Badge label="MCP" tone="cyan" />}{tool.byok && <Badge label="BYOK" tone="amber" />}{(tool.free || tool.free_tier) && <Badge label="Free" tone="green" />}{tool.vscode && <Badge label="VS Code" tone="blue" />}{tool.cli && <Badge label="CLI" tone="violet" />}</div></Link> }
function Badge({ label }: { label: string; tone: string }) { return <span className="rounded-md bg-[#f5c542]/10 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-[#f5c542]">{label}</span> }